"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.barangRoute = void 0;
const express_1 = require("express");
const barangController_1 = require("../controllers/barangController");
const authMiddleware_1 = require("../middleware/authMiddleware");
const router = (0, express_1.Router)();
exports.barangRoute = router;
router.get("/", authMiddleware_1.auth, barangController_1.index);
router.get("/satuan/:id", authMiddleware_1.auth, barangController_1.getSatuan);
router.get("/option", authMiddleware_1.auth, barangController_1.getOption);
router.get("/:id", authMiddleware_1.auth, barangController_1.show);
router.post("/", authMiddleware_1.auth, barangController_1.store);
router.patch("/:id", authMiddleware_1.auth, barangController_1.update);
router.delete("/:id", authMiddleware_1.auth, barangController_1.destroy);
